TiendaMvc/Controllers/AlmacenController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaMvc.Filtros;
using TiendaMvc.Models;

namespace TiendaMvc.Controllers
{
    public class AlmacenController : BaseController
    {

        // Conexion a base de datos con Entity
        private Tienda25Entities db = new Tienda25Entities();

        public ActionResult Productos()
        {
            
            // Asigno al ViewBag etiquetas
            ViewBag.etiquetas = db.Etiqueta.ToList();
            // Asigno al ViewBag almacenes
            ViewBag.almacenes = db.Almacen.ToList();

            var data = db.Producto;
            return View(data);
        }

        // GET: Listado de almacenes
        public ActionResult Index()
        {


            //almacenProducto.Find(o => o.Etiqueta.Equals())
            // obtener almacen producto
            ViewBag.productos = db.Producto.ToList();
            // obtener listado de etiquetas
            var info = db.Etiqueta;
            // guardo objeto en ViewBag
            ViewBag.etiquetas = info.ToList();
            ViewData["Titulo"] = "Listado de almacenes"; 

            var data = db.Almacen;
            return View(data);
        }

        [FiltroId] // aplica este filtro
        // para cargar el formulario
        public ActionResult Modificar(int? id)
        {
            var data = db.Almacen.Find(id);
            return View(data);
        }


        
        // para guardar el almacen
        [HttpPost]
        [ValidateAntiForgeryToken] // genera un token
        public ActionResult Modificar(Almacen model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified; // indica el estado en que esta el objeto = Modified
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Borrar(int id)
        {
            var data = db.Almacen.Find(id);
            if (data.Almacen_Producto.Any()) // si hay algun registro
                db.Almacen_Producto.RemoveRange(data.Almacen_Producto); // hago borrado en cascada

            db.Almacen.Remove(data);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //public ActionResult Detalle(int id)
        //{
        //    var data = db.Almacen.Find(id);
        //    return View(data);
        //}

        //[HttpPost] // Unicamente por Post
        //// llega la petición desde Http
        //public ActionResult Actualizar(Almacen model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Almacen.Add(model);
        //        db.SaveChanges();
        //        // porque si guarda podrias crear otro, es como limpiar el formulario
        //        return View(new Almacen());
        //    }
        //    // por defecto esta el formulario para corregirlo
        //    return View(model);
        //}

        
        //// llega la petición desde Http
        //public ActionResult Borrar(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Almacen almacen = db.Almacen.Find(id);
        //    if (almacen == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(almacen);
        //}

        //// POST: Almacen/Borrar/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult BorrarConfirmed(int id)
        //{
        //    var data = db.Almacen.Find(id);
        //    db.Almacen.Remove(data);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //public ActionResult Editar(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Almacen almacen = db.Almacen.Find(id);
        //    if (almacen == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(almacen);
        //}




    }
}

TiendaMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("MiJavaScript", false)
</body>
</html>

TiendaMvc/Views/Shared/_fichaAlmacen.cshtml
@model TiendaMvc.Models.Almacen

<div class="col-md-3">
    <h3>@Html.DisplayFor(o => Model.nombre) </h3>
    <p>
        @Html.DisplayFor(o => Model.ciudad)
        @Html.DisplayFor(o => Model.codigo_postal)
    </p>
    <p>
        @Html.ActionLink("Modificar", "Modificar", "Almacen",
        new { id = Model.id_almacen },null)

        <a href="#" class="borrame" data-id="@Model.id_almacen">
            Borrar
        </a>
    </p>

</div>
    